# Generated by Django 6.0.7 on 2026-08-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Single Room', 'Single Room'), ('Deluxe Room', 'Deluxe Room'), ('Luxury Room', 'Luxury Room'), ('Executive Room', 'Executive Room'), ('Family Suite', 'Family Suite'), ('Presidential Suite', 'Presidential Suite')], max_length=20),
        ),
    ]
